# Generated by Django 3.1.7 on 2021-04-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=15)),
                ('Password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, max_length=300, null=True, upload_to='DevImgs/')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='1', max_length=20)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Mno', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='')),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(default='', max_length=150)),
                ('Project_Detail', models.CharField(default='', max_length=500)),
                ('Project_Modules_need', models.PositiveIntegerField(default=0)),
                ('Project_Modules_Done', models.PositiveIntegerField(default=0)),
                ('Project_Progress', models.CharField(default='Pending', max_length=100)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('project_request', models.BooleanField(default=False)),
                ('developer_request', models.BooleanField(default=False)),
                ('tester_request', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, max_length=300, null=True, upload_to='PmImgs/')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='1', max_length=20)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Mno', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='')),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_name', models.CharField(default='', max_length=15)),
                ('Type_Details', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, max_length=300, null=True, upload_to='TestImgs/')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='1', max_length=20)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Mno', models.CharField(default='', max_length=100)),
                ('Address', models.TextField(default='')),
                ('Password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StackOverFlowQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='', max_length=500)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('devl', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.developer')),
                ('pmanage', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.project_manager')),
                ('tset', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tester')),
            ],
        ),
        migrations.CreateModel(
            name='StackOverFlowAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField(default='')),
                ('Answer_doc', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='SOFA/')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('Questions', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stackoverflowquestion')),
                ('devl', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.developer')),
                ('pmanage', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.project_manager')),
                ('tset', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tester')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Name', models.CharField(default='', max_length=150)),
                ('Module_Detail', models.CharField(default='', max_length=500)),
                ('Progress', models.PositiveIntegerField(default=0)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('developer_request', models.BooleanField(default=False)),
                ('tester_request', models.BooleanField(default=False)),
                ('Pm_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.project_manager')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.developer')),
                ('pd_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.project_details')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tester')),
            ],
        ),
        migrations.AddField(
            model_name='project_details',
            name='Pm_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.project_manager'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='Pt_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.project_type'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='dev_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.developer'),
        ),
        migrations.AddField(
            model_name='project_details',
            name='tset_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tester'),
        ),
        migrations.CreateModel(
            name='Models_Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField(default='')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat_doc', models.FileField(blank=True, default='', max_length=300, null=True, upload_to='Chats/')),
                ('devl', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.developer')),
                ('mod', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.project_module')),
                ('proj', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.project_details')),
                ('tset', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tester')),
            ],
        ),
    ]
